// Generated by gencpp from file turtle_bot_4/turtle_bot_player.msg
// DO NOT EDIT!


#ifndef TURTLE_BOT_4_MESSAGE_TURTLE_BOT_PLAYER_H
#define TURTLE_BOT_4_MESSAGE_TURTLE_BOT_PLAYER_H

#include <ros/service_traits.h>


#include <turtle_bot_4/turtle_bot_playerRequest.h>
#include <turtle_bot_4/turtle_bot_playerResponse.h>


namespace turtle_bot_4
{

struct turtle_bot_player
{

typedef turtle_bot_playerRequest Request;
typedef turtle_bot_playerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct turtle_bot_player
} // namespace turtle_bot_4


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtle_bot_4::turtle_bot_player > {
  static const char* value()
  {
    return "de8e7c90c40bd1c3b6a3104b4ac68f54";
  }

  static const char* value(const ::turtle_bot_4::turtle_bot_player&) { return value(); }
};

template<>
struct DataType< ::turtle_bot_4::turtle_bot_player > {
  static const char* value()
  {
    return "turtle_bot_4/turtle_bot_player";
  }

  static const char* value(const ::turtle_bot_4::turtle_bot_player&) { return value(); }
};


// service_traits::MD5Sum< ::turtle_bot_4::turtle_bot_playerRequest> should match
// service_traits::MD5Sum< ::turtle_bot_4::turtle_bot_player >
template<>
struct MD5Sum< ::turtle_bot_4::turtle_bot_playerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtle_bot_4::turtle_bot_player >::value();
  }
  static const char* value(const ::turtle_bot_4::turtle_bot_playerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtle_bot_4::turtle_bot_playerRequest> should match
// service_traits::DataType< ::turtle_bot_4::turtle_bot_player >
template<>
struct DataType< ::turtle_bot_4::turtle_bot_playerRequest>
{
  static const char* value()
  {
    return DataType< ::turtle_bot_4::turtle_bot_player >::value();
  }
  static const char* value(const ::turtle_bot_4::turtle_bot_playerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtle_bot_4::turtle_bot_playerResponse> should match
// service_traits::MD5Sum< ::turtle_bot_4::turtle_bot_player >
template<>
struct MD5Sum< ::turtle_bot_4::turtle_bot_playerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtle_bot_4::turtle_bot_player >::value();
  }
  static const char* value(const ::turtle_bot_4::turtle_bot_playerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtle_bot_4::turtle_bot_playerResponse> should match
// service_traits::DataType< ::turtle_bot_4::turtle_bot_player >
template<>
struct DataType< ::turtle_bot_4::turtle_bot_playerResponse>
{
  static const char* value()
  {
    return DataType< ::turtle_bot_4::turtle_bot_player >::value();
  }
  static const char* value(const ::turtle_bot_4::turtle_bot_playerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLE_BOT_4_MESSAGE_TURTLE_BOT_PLAYER_H
