// Generated by gencpp from file proyecto/points.msg
// DO NOT EDIT!


#ifndef PROYECTO_MESSAGE_POINTS_H
#define PROYECTO_MESSAGE_POINTS_H

#include <ros/service_traits.h>


#include <proyecto/pointsRequest.h>
#include <proyecto/pointsResponse.h>


namespace proyecto
{

struct points
{

typedef pointsRequest Request;
typedef pointsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct points
} // namespace proyecto


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::proyecto::points > {
  static const char* value()
  {
    return "177fc52e6c64d96dce1a98062c347269";
  }

  static const char* value(const ::proyecto::points&) { return value(); }
};

template<>
struct DataType< ::proyecto::points > {
  static const char* value()
  {
    return "proyecto/points";
  }

  static const char* value(const ::proyecto::points&) { return value(); }
};


// service_traits::MD5Sum< ::proyecto::pointsRequest> should match
// service_traits::MD5Sum< ::proyecto::points >
template<>
struct MD5Sum< ::proyecto::pointsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::proyecto::points >::value();
  }
  static const char* value(const ::proyecto::pointsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::proyecto::pointsRequest> should match
// service_traits::DataType< ::proyecto::points >
template<>
struct DataType< ::proyecto::pointsRequest>
{
  static const char* value()
  {
    return DataType< ::proyecto::points >::value();
  }
  static const char* value(const ::proyecto::pointsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::proyecto::pointsResponse> should match
// service_traits::MD5Sum< ::proyecto::points >
template<>
struct MD5Sum< ::proyecto::pointsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::proyecto::points >::value();
  }
  static const char* value(const ::proyecto::pointsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::proyecto::pointsResponse> should match
// service_traits::DataType< ::proyecto::points >
template<>
struct DataType< ::proyecto::pointsResponse>
{
  static const char* value()
  {
    return DataType< ::proyecto::points >::value();
  }
  static const char* value(const ::proyecto::pointsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PROYECTO_MESSAGE_POINTS_H
