// Generated by gencpp from file proyecto/pointsRequest.msg
// DO NOT EDIT!


#ifndef PROYECTO_MESSAGE_POINTSREQUEST_H
#define PROYECTO_MESSAGE_POINTSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace proyecto
{
template <class ContainerAllocator>
struct pointsRequest_
{
  typedef pointsRequest_<ContainerAllocator> Type;

  pointsRequest_()
    : param()  {
    }
  pointsRequest_(const ContainerAllocator& _alloc)
    : param(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _param_type;
  _param_type param;





  typedef boost::shared_ptr< ::proyecto::pointsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::proyecto::pointsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct pointsRequest_

typedef ::proyecto::pointsRequest_<std::allocator<void> > pointsRequest;

typedef boost::shared_ptr< ::proyecto::pointsRequest > pointsRequestPtr;
typedef boost::shared_ptr< ::proyecto::pointsRequest const> pointsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::proyecto::pointsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::proyecto::pointsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::proyecto::pointsRequest_<ContainerAllocator1> & lhs, const ::proyecto::pointsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.param == rhs.param;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::proyecto::pointsRequest_<ContainerAllocator1> & lhs, const ::proyecto::pointsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace proyecto

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::proyecto::pointsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::proyecto::pointsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::proyecto::pointsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::proyecto::pointsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::proyecto::pointsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::proyecto::pointsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::proyecto::pointsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb04b7504512676dca105ab8842899a4";
  }

  static const char* value(const ::proyecto::pointsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb04b7504512676dULL;
  static const uint64_t static_value2 = 0xca105ab8842899a4ULL;
};

template<class ContainerAllocator>
struct DataType< ::proyecto::pointsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "proyecto/pointsRequest";
  }

  static const char* value(const ::proyecto::pointsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::proyecto::pointsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string param\n"
;
  }

  static const char* value(const ::proyecto::pointsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::proyecto::pointsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.param);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pointsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::proyecto::pointsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::proyecto::pointsRequest_<ContainerAllocator>& v)
  {
    s << indent << "param: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.param);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROYECTO_MESSAGE_POINTSREQUEST_H
