// Generated by gencpp from file proyecto/pointsResponse.msg
// DO NOT EDIT!


#ifndef PROYECTO_MESSAGE_POINTSRESPONSE_H
#define PROYECTO_MESSAGE_POINTSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace proyecto
{
template <class ContainerAllocator>
struct pointsResponse_
{
  typedef pointsResponse_<ContainerAllocator> Type;

  pointsResponse_()
    : coords()  {
    }
  pointsResponse_(const ContainerAllocator& _alloc)
    : coords(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _coords_type;
  _coords_type coords;





  typedef boost::shared_ptr< ::proyecto::pointsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::proyecto::pointsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct pointsResponse_

typedef ::proyecto::pointsResponse_<std::allocator<void> > pointsResponse;

typedef boost::shared_ptr< ::proyecto::pointsResponse > pointsResponsePtr;
typedef boost::shared_ptr< ::proyecto::pointsResponse const> pointsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::proyecto::pointsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::proyecto::pointsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::proyecto::pointsResponse_<ContainerAllocator1> & lhs, const ::proyecto::pointsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.coords == rhs.coords;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::proyecto::pointsResponse_<ContainerAllocator1> & lhs, const ::proyecto::pointsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace proyecto

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::proyecto::pointsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::proyecto::pointsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::proyecto::pointsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::proyecto::pointsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::proyecto::pointsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::proyecto::pointsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::proyecto::pointsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "193060e1db15ff0c954723b48c3a941b";
  }

  static const char* value(const ::proyecto::pointsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x193060e1db15ff0cULL;
  static const uint64_t static_value2 = 0x954723b48c3a941bULL;
};

template<class ContainerAllocator>
struct DataType< ::proyecto::pointsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "proyecto/pointsResponse";
  }

  static const char* value(const ::proyecto::pointsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::proyecto::pointsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string coords\n"
;
  }

  static const char* value(const ::proyecto::pointsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::proyecto::pointsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.coords);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pointsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::proyecto::pointsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::proyecto::pointsResponse_<ContainerAllocator>& v)
  {
    s << indent << "coords: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.coords);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROYECTO_MESSAGE_POINTSRESPONSE_H
